name: Weekly Git Cleanup

on:
  schedule:
    - cron: '0 3 * * 1'  # 毎週月曜 AM3:00 UTC（JST: 月曜 12時）
  workflow_dispatch:       # ← 手動実行可能にする

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0  # 全履歴を取得（Squashに必要）

    - name: Reset commit history
      run: |
        git config --global user.name "rss-cleaner"
        git config --global user.email "cleaner@example.com"
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
        git reset --soft $(git rev-list --max-parents=0 HEAD)
        git commit -m "Weekly squash commit"
        git push --force
